name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
jobs:
  zig:
    name: Prebuild zig
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 21]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install --build-from-source

      - name: Package prebuild
        run: |
          export CC="zig cc -target aarch64-linux-gnu"
          export CXX="zig cc -target aarch64-linux-gnu"
          
          npx node-pre-gyp --target_arch=arm64 configure build package
